stages:
  - build
  - package

build:
  stage: build
  image: node:20-alpine
  script:
    - npm i

package:
  stage: package
  image: docker:27
  services:
    - docker:27-dind
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login registry.gitlab.com -u "$CI_REGISTRY_USER" --password-stdin
    - docker build -f infrastructure/Dockerfile -t $CI_REGISTRY_IMAGE/frontend:latest .
    - docker push $CI_REGISTRY_IMAGE/frontend:latest
