stages:
  - build
  - package

variables:
  MAJOR: "1"
  MINOR: "0"

build:
  stage: build
  image: node:20-alpine
  script:
    - npm i
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_DEFAULT_BRANCH == $CI_COMMIT_BRANCH

package:
  stage: package
  image: docker:27
  services:
    - docker:27-dind
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
  script:
    - DATE=$(date +%Y%m%d)
    - VERSION="$MAJOR.$MINOR.$DATE-$CI_PIPELINE_ID"
    - echo "Building version $VERSION"
    - echo "$CI_REGISTRY_PASSWORD" | docker login registry.gitlab.com -u "$CI_REGISTRY_USER" --password-stdin
    - docker build -f infrastructure/Dockerfile \
      -t $CI_REGISTRY_IMAGE/frontend:$VERSION \
      -t $CI_REGISTRY_IMAGE/frontend:latest .
    - docker push $CI_REGISTRY_IMAGE/frontend:$VERSION
    - docker push $CI_REGISTRY_IMAGE/frontend:latest
  rules:
    - if: $CI_DEFAULT_BRANCH == $CI_COMMIT_BRANCH && $CI_PIPELINE_SOURCE != "merge_request_event"